export const CUST_LOGIN_REQUEST = "CUST_LOGIN_REQUEST";
export const CUST_LOGIN_SUCCESS = "CUST_LOGIN_SUCCESS";
export const CUST_LOGIN_FAIL = "CUST_LOGIN_FAIL";
export const CUST_LOGOUT = "CUST_LOGOUT";
export const CUST_REGISTER_REQUEST = "CUST_REGISTER_REQUEST";
export const CUST_REGISTER_SUCCESS = "CUST_REGISTER_SUCCESS";
export const CUST_REGISTER_FAIL = "CUST_REGISTER_FAIL";

export const CUST_DETAILS_REQUEST = "CUST_DETAILS_REQUEST";
export const CUST_DETAILS_SUCCESS = "CUST_DETAILS_SUCCESS";
export const CUST_DETAILS_FAIL = "CUST_DETAILS_FAIL";

export const CUST_UPDATE_PROFILE_REQUEST = "CUST_UPDATE_PROFILE_REQUEST";
export const CUST_UPDATE_PROFILE_SUCCESS = "CUST_UPDATE_PROFILE_SUCCESS";
export const CUST_UPDATE_PROFILE_FAIL = "CUST_UPDATE_PROFILE_FAIL";
export const CUST_UPDATE_PROFILE_RESET = "CUST_UPDATE_PROFILE_RESET";
