export const CUST_LOGIN_REQUEST = "CUST_LOGIN_REQUEST";
export const CUST_LOGIN_SUCCESS = "CUST_LOGIN_SUCCESS";
export const CUST_LOGIN_FAIL = "CUST_LOGIN_FAIL";
export const CUST_LOGOUT = "CUST_LOGOUT";
